#!/bin/bash

while :

do
        ps aux | grep "Main_program.py"  > /dev/null 2&>1
        if [[ "$?" == "0" ]]; then
                echo "It is already running"
        elif [[ "$?" == "1" ]]; then
                echo "It has stopped running. Re-running script now..."
                sudo python Main_program.py
        fi
done



